apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: coffee-dev
  namespace: argo
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: https://github.com/PeppyDays/sample-gitops.git
      revision: main
      directories:
      - path: gitops/argo/applications/coffee/*
      requeueAfterSeconds: 20
  syncPolicy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: '{{ .path.basenameNormalized }}-dev'
      name: '{{ .path.basenameNormalized }}-dev'
      namespace: argo
    spec:
      project: coffee
      source:
        repoURL: https://github.com/PeppyDays/sample-gitops.git
        path: '{{ .path.path }}/overlays/dev'
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: coffee-dev
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
      syncOptions:
      - allowEmpty=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: coffee-prod
  namespace: argo
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: https://github.com/PeppyDays/sample-gitops.git
      revision: main
      directories:
      - path: gitops/argo/applications/coffee/*
      requeueAfterSeconds: 20
  syncPolicy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: '{{ .path.basenameNormalized }}-prod'
      name: '{{ .path.basenameNormalized }}-prod'
      namespace: argo
    spec:
      project: coffee
      source:
        repoURL: https://github.com/PeppyDays/sample-gitops.git
        path: '{{ .path.path }}/overlays/prod'
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: coffee-prod
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
      syncOptions:
      - allowEmpty=true
