apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: "-2"
  name: coffee
  namespace: argo
spec:
  description: Coffee product
  sourceRepos:
  - '*'
  destinations:
  - server: https://kubernetes.default.svc
    name: in-cluster
    namespace: coffee-*
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
