apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- bootstrap/cluster-resources/
- bootstrap/argo-cd/
- bootstrap/argo-resources/
- bootstrap/cluster-resources.yaml
- bootstrap/argo-cd.yaml
- bootstrap/argo-resources.yaml
- bootstrap/applications.yaml
