on:
  workflow_dispatch:

name: Coffee Cart Deploy to Production

jobs:
  build:
    name: Deploy Coffee Cart
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Production
      run: |
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git pull origin main --rebase
        
        pushd ./gitops/argo/applications/coffee/cart/overlays/prod
        kustomize edit set image ghcr.io/peppydays/coffee/cart:${{ github.sha }}
        
        git add kustomization.yaml
        git commit -m "Updated Coffee Cart image to ${{ github.sha }}"
        git push origin main
