on:
  workflow_dispatch:
  pull_request:
    branches:
    - '!main'
    paths:
    - 'products/coffee/order/**'
    - '.github/workflows/coffee_order_build.yaml'
  push:
    branches:
    - '!main'
    paths:
    - 'products/coffee/order/**'
    - '.github/workflows/coffee_order_build.yaml'

name: Coffee Order Test

jobs:
  build:
    name: Test Coffee Order
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./products/coffee/order
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test
      run: cargo test
