apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  users.anonymous.enabled: "false"
  passwordPattern: "^.{7,32}$"
  accounts.admin: apiKey
  configManagementPlugins: |
    - name: kustomize-build-with-helm
      generate:
        command: [ "sh", "-c" ]
        args: [ "kustomize build --enable-helm" ]
