apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-rollouts
resources:
  - base/namespaces.yaml
  - https://raw.githubusercontent.com/argoproj/argo-rollouts/v1.4.0/manifests/install.yaml
