apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: sample-dev
  namespace: argo
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: https://github.com/PeppyDays/sample-gitops.git
      revision: main
      directories:
      - path: gitops/argo/applications/sample/*
      requeueAfterSeconds: 20
  syncPolicy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: '{{ .path.basenameNormalized }}-dev'
      name: '{{ .path.basenameNormalized }}-dev'
      namespace: argo
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: sample-dev
      ignoreDifferences:
      - group: argoproj.io
        jsonPointers:
        - /status
        kind: Application
      project: sample
      source:
        repoURL: https://github.com/PeppyDays/sample-gitops.git
        path: '{{ .path.path }}'
        targetRevision: main
        helm:
          valueFiles:
          - values-dev.yaml
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: sample-prod
  namespace: argo
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: https://github.com/PeppyDays/sample-gitops.git
      revision: main
      directories:
      - path: gitops/argo/applications/sample/*
      requeueAfterSeconds: 20
  syncPolicy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: '{{ .path.basenameNormalized }}-prod'
      name: '{{ .path.basenameNormalized }}-prod'
      namespace: argo
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: sample-prod
      ignoreDifferences:
      - group: argoproj.io
        jsonPointers:
        - /status
        kind: Application
      project: sample
      source:
        repoURL: https://github.com/PeppyDays/sample-gitops.git
        path: '{{ .path.path }}'
        targetRevision: main
        helm:
          valueFiles:
          - values-prod.yaml
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
