apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: coffee
  name: coffee
  namespace: argo
spec:
  project: platform
  source:
    repoURL: https://github.com/PeppyDays/sample-gitops.git
    path: gitops/argo/products/coffee
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true
