apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: sample
  name: sample
  namespace: argo
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: argoproj.io
    jsonPointers:
    - /status
    kind: Application
  project: platform
  source:
    repoURL: https://github.com/PeppyDays/sample-gitops.git
    path: gitops/argo/products/sample
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true
