apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: coffee-dev
resources:
- ../../base

patches:
- path: deployment.yaml
  target:
    kind: Deployment
    name: cart

images:
- name: ghcr.io/peppydays/coffee/cart
  newTag: 9b71ed56259b7e1479f63ea234f6e88f29d1e9ad
