apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: coffee-dev
resources:
- ../../base

patches:
- path: deployment.yaml
  target:
    kind: Deployment
    name: cart

images:
- name: cart
  newName: cart
  newTag: latest
- name: ghcr.io/peppydays/coffee/cart
  newTag: 5d7e451b5302e74052c4679f2dc0ff8a287189d6
