apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo

resources:
- https://raw.githubusercontent.com/argoproj/argo-rollouts/v1.4.1/manifests/install.yaml

patches:
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRoleBinding
  patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: argo
