on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - 'products/coffee/cart/**'
    - '.github/workflows/coffee_cart_build.yaml'

name: Coffee Cart Build

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Coffee Cart
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
#    - name: Log in to GitHub Container Registry
#      uses: docker/login-action@v2
#      with:
#        registry: ghcr.io
#        username: ${{ github.repository_owner }}
#        password: ${{ secrets.GHCR_TOKEN }}
    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: ./products/coffee/cart
        file: ./products/coffee/cart/Dockerfile
        platforms: linux/amd64,linux/arm64,darwin
        push: true
        tags: |
          ghcr.io/peppydays/coffee/cart:${{ github.sha }}
          ghcr.io/peppydays/coffee/cart:latest
        cache-from: type=registry,ref=ghcr.io/peppydays/coffee/cart:cache
        cache-to: type=registry,ref=ghcr.io/peppydays/coffee/cart:cache,mode=max
    - name: Deploy to Dev
      run: |
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git pull origin main --rebase
        
        pushd ./gitops/argo/applications/coffee/cart/overlays/dev
        kustomize edit set image ghcr.io/peppydays/coffee/cart:${{ github.sha }}

        git add kustomization.yaml
        git commit -m "Updated Coffee Cart image to ${{ github.sha }}"
        git push origin main
