on:
  workflow_dispatch:
  pull_request:
    branches:
    - '!main'
    paths:
    - 'products/coffee/cart/**'
    - '.github/workflows/coffee_cart_build.yaml'
  push:
    branches:
    - '!main'
    paths:
    - 'products/coffee/cart/**'
    - '.github/workflows/coffee_cart_build.yaml'

name: Coffee Cart Test

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Test Coffee Cart
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./products/coffee/cart
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Test
      run: cargo test --verbose
