on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - 'products/coffee/cart/**'
    - '.github/workflows/coffee_cart_build.yaml'

name: Coffee Cart Build

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Coffee Cart
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./products/coffee/cart
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./products/coffee/cart/Dockerfile
        push: true
        tags: |
          ghcr.io/peppydays/coffee/cart:${GITHUB_SHA::7}
          ghcr.io/peppydays/coffee/cart:latest
#    - name: Build and Push
#      run: |
#        docker build -t cart .
#        docker tag cart ghcr.io/peppydays/coffee/cart:${GITHUB_SHA::7}
#        docker tag cart ghcr.io/peppydays/coffee/cart:latest
#        docker push ghcr.io/peppydays/coffee/cart:${GITHUB_SHA::7}
#        docker push ghcr.io/peppydays/coffee/cart:latest
#    - name: Deploy to Dev
