on:
  pull_request:
    paths:
    - 'products/coffee/cart/**'
    - 'products/coffee/order/**'

name: Modular Deploy

jobs:
  detect-module-changes:
    name: Detect Module Changes
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      changed-modules: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          cart:
          - 'products/coffee/cart/**'
          order:
          - 'products/coffee/order/**'
  deploy:
    name: Build and Push
    runs-on: ubuntu-latest
    needs:
    - detect-module-changes
    permissions:
      id-token: write
      contents: read
    steps:
#    - name: get the output
#      env:
#        DETECTED_MODULES_CHANGE: ${{ fromJson(needs.detect-module-changes.outputs.changed-modules) }}
#      run: |
#        echo "The following modules have changed: $DETECTED_MODULES_CHANGE"
    - name: script
      run: |
        DETECTED_MODULES_CHANGE='${{ needs.detect-module-changes.outputs.changed-modules }}'
        DETECTED_MODULES=${DETECTED_MODULES_CHANGE//[\"\[\]]/}
        IFS=','
        for module in $DETECTED_MODULES; do
          echo "project/to/service/$module/dev/values.yaml"
        done
