on:
  pull_request:
    branches:
    - arine/**
    paths:
    - 'products/coffee/cart/**'
    - 'products/coffee/order/**'

name: Modular Deploy

jobs:
  detect-module-changes:
    name: Detect Module Changes
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      changed-modules: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          cart:
          - 'products/coffee/cart/**'
          order:
          - 'products/coffee/order/**'
  deploy:
    name: Build and Push
    runs-on: ubuntu-latest
    needs:
    - detect-module-changes
    permissions:
      id-token: write
      contents: read
    steps:
    - name: get the output
      run: |
        echo "The following modules have changed: ${{ needs.detect-module-changes.outputs.changed-modules }}"
